apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv-volume
  namespace: gitlab
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/redis"
